# -*- coding: utf-8 -*-
"""criando um mapa das sete maravilha do mundo.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xmSYIpF-bTChTHuoE2UFvIFeCXaXOQBr
"""

import folium # type: ignore
from folium import plugins # type: ignore

sete_maravilhas = ["Grande Muralha da China",
                   "Cristo Redentor","Machu Picchu",
                   "Chichén Itzá","Coliseu","Petra",
                   "Taj Mahal"]

cord_lugar = [[40.43205466910793, 116.5703534380663],
              [-22.951649233528503, -43.21050866252006],
              [-13.162979372949751, -72.54525140061105],
              [20.679466143446703, -88.5684340048395],
              [41.890369907457774, 12.492284539998344],
              [30.32867662749265, 35.4443514664021],
              [27.17543111199757, 78.04217438161723]]

local_map = folium.Map(location=[21.2894, -21.0938], zoom_start=2, control_scale=True, tiles="cartodbpositron")
#folium.TileLayer('Cartodbpositron').add_to(local_map)
'''
folium.TileLayer(tiles= 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
                 attr=  '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
                 name= "OpenStreetMap.Mapnik").add_to(local_map)

folium.LayerControl().add_to(local_map)
 '''
for i in range(len(cord_lugar)):
  coordenada = cord_lugar[i]
  maravilha = sete_maravilhas[i]
  folium.Marker(coordenada, popup=maravilha, icon= folium.Icon(icon="glyphicon glyphicon-camera",
                                                              color= "black",
                                                              icon_color="white",
                                                              prefix="glyphicon")).add_to(local_map)
local_map.add_child(folium.LatLngPopup())
local_map.save("Sete_Maravilhas.html")
local_map

"""# Nova seção"""

from google.colab import drive # type: ignore
drive.mount('/content/drive')

local_map = folium.Map(location=[-22.951649233528503, -43.21050866252006], zoom_start=5, control_scale=True, tiles="Cartodbpositron")
local_map